[DEFAULT]
transport_url = rabbit://openstack:NZyHCGmxnswCJ9Q4B2NlpBch3qBocdefxD5PnLMk@192.168.56.20:5672/
rpc_backend = rabbit

rabbit_host = 192.168.56.20
rabbit_port = 5672
rabbit_userid = openstack
rabbit_password = NZyHCGmxnswCJ9Q4B2NlpBch3qBocdefxD5PnLMk
control_exchange = trove
log_dir = /var/log/trove
log_file = guestagent.log
debug = flase
management_networks = 50c2b945-f83d-4ca9-bafe-ade20fae4068

[oslo_messaging_rabbit]
rabbit_retry_interval = 1
rabbit_retry_backoff = 2
rabbit_interval_max = 30
heartbeat_timeout_threshold = 60
rabbit_quorum_queue = true
rabbit_stream_fanout = true
rabbit_qos_prefetch_count = 1
rabbit_transient_quorum_queue = true

[oslo_concurrency]
lock_path = /var/lib/trove/tmp

[service_credentials]
auth_url = http://192.168.56.30:5000/v3
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = trove
password = soVj9uodmTyQKz5U4rtZ8fslijmpPlVBxUTy5akY
region_name = RegionOne

[database]
connection = mysql+pymysql://trove:w3ZZUkfgHsSko1aCAhQVthP6AGcwNNxZUG915zeh@192.168.56.30:3306/trove

